film20/upload/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns( 'film20.upload.views',
    url( r'^upload/image/$', 'upload_image', name='upload-image' ),
    url( r'^upload/picture/$', 'upload_picture', name='upload-picture' ),
)

film20/urls.py
#-------------------------------------------------------------------------------
# Filmaster - a social web network and recommendation engine
# Copyright (c) 2009 Filmaster (Borys Musielak, Adam Zielinski).
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------
from django.conf.urls.defaults import *

#from django.contrib.comments.models import FreeComment
from film20.config.urls import *
from film20.account.urls import *
from film20.core.urls import *
from film20.blog.urls import *
from film20.filmbasket.urls import *
from film20.regional_info.urls import *

from film20.recommendations.urls import *
from film20.event.urls import *
from film20.contest.urls import *
from film20.import_films.urls import *
from film20.externallink.urls import *
from film20.moderation.urls import urlpatterns as moderationpatterns
from film20.merging_tools.urls import urlpatterns as mergingtoolspatterns
from film20.add_films.urls import urlpatterns as addfilmspatterns
from film20.followers.urls import *
from film20.search.urls import *
from film20.posters.urls import *
from film20.register.urls import *
from film20.sitemap import sitemappatterns
from film20.dashboard.urls import *
from film20.legacy_redirects.urls import *
from film20.threadedcomments.urls import urlpatterns as threadedcommentspatterns
from film20.messages.urls import urlpatterns as messagespatterns
from film20.upload.urls import urlpatterns as uploadpatterns
from film20.facebook_connect.urls import root_urlpatterns as fbpatterns
from film20.useractivity.urls import urlpatterns as activity_patterns

from django.conf import settings
LOCAL = settings.LOCAL
from django.views.generic.list_detail import object_list
from django.contrib import admin

from django import template
template.add_to_builtins('film20.core.templatetags.utils')

admin.autodiscover()

urlpatterns = patterns('',

    # rejestracja: TODO: przeniesc
#    (r'^', include('film20.userprofile.urls')),

    # Uncomment this for admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^fb/', include('film20.facebook_connect.urls')),
    (r'^ping/$', 'film20.core.views.ping'),
    url(r'^%(SETTINGS)s/' % urls, include('film20.usersettings.urls')),
    url(r'^%(PW)s/' % urls, include('film20.messages.urls')),
    url(r'^%(SHOWTIMES)s/' % urls, include('film20.showtimes.urls')),
    url(r'^%(SHOW_FESTIVAL)s/(?P<permalink>[\w\-_]+)/' % urls, include('film20.festivals.urls')),
    url(r'^%(SHOW_PROFILE)s/(?P<username>[\w\-_]+)/' % urls, include('film20.publicprofile.urls')),

    # TODO: is this necessary ??
    url(r'^(?P<content_type>\d+)/(?P<object_id>\d+)/$', 'film20.threadedcomments.views.comment', name="tc_comment"),
)

# account
urlpatterns += accountpatterns 

# core
urlpatterns += corepatterns 

urlpatterns += legacyredirectspatterns

urlpatterns += fbpatterns
urlpatterns += recompatterns
urlpatterns += filmbasketpatterns
urlpatterns += eventpatterns
urlpatterns += contestpatterns
urlpatterns += importfilmspatterns
urlpatterns += externallinkpatterns
urlpatterns += regionalinfopatterns
urlpatterns += sitemappatterns
urlpatterns += followpatterns
urlpatterns += searchpatterns
urlpatterns += posterpatterns
urlpatterns += moderationpatterns
urlpatterns += mergingtoolspatterns
urlpatterns += registerpatterns
urlpatterns += addfilmspatterns
urlpatterns += dashboardpatterns
urlpatterns += threadedcommentspatterns
urlpatterns += uploadpatterns
urlpatterns += activity_patterns

never_cache(admin.site.urls)

if LOCAL:
    import os
    BASE_DIR = os.path.abspath(os.path.dirname(__file__))
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(BASE_DIR,'static')}),
    )

js_info_dict = {
    'packages': (),
}

urlpatterns += patterns('',
    #(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    (r'^jsi18n/((?P<packages>\S+?)/)?$', 'django.views.i18n.javascript_catalog'),
)

urlpatterns += patterns('',
  url('^oauth/', include('film20.api.oauth_urls')),
)

urlpatterns += patterns('',
  url(r'^view-sql/(?P<key>.*)/$', 'film20.utils.sql.view_sql', name='view_sql'),
)

from film20.api.urls import urlpatterns as api_patterns
urlpatterns += patterns('',
  url(r'^api/', include(api_patterns)),
)

urlpatterns += patterns('',
  url('^account/logout/$', 'film20.account.views.logout'),
)

try:
  import film20.local
  urlpatterns += film20.local.urlpatterns
except:
  pass

handler500 = 'film20.core.views.handler500'
handler404 = 'film20.core.views.handler404'

film20/upload/models.py
from os import path

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import filesizeformat

def get_upload_path( instance, filename ):
    if len( filename ) > 60:
        basename, extension = path.splitext( filename )
        filename = "%s%s" % ( filename[:50], extension )

    return "uploads/%s/%s" % ( filename[0], filename )

class UploadedImage( models.Model ):
    image = models.ImageField( _( "Image" ), upload_to=get_upload_path )
    uploaded_at = models.DateTimeField( _( "Uploaded at" ), auto_now_add=True )

    class Meta:
        abstract = True

    def __unicode__( self ):
        return u"%s" % ( self.file )
    
    @property
    def size( self ):
        return filesizeformat( self.file.size )

class UserUploadedImage( UploadedImage ):
    uploaded_by = models.ForeignKey( User, verbose_name=_( "Uploaded by" ) )
    
    class Meta( UploadedImage.Meta ):
        verbose_name = _( "User uploaded image" )

film20/upload/forms.py
import mimetypes, urllib

from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.files.images import get_image_dimensions
from django.core.files.uploadedfile import SimpleUploadedFile

from .models import UserUploadedImage

# TODO settings
THUMBNAIL_DIMENSION = ( 61, 102 )

class UserUploadImageForm( forms.ModelForm ):

    image = forms.ImageField( required = False )
    url = forms.URLField( required = False )

    class Meta:
        model = UserUploadedImage
        fields = ( 'image', )

    def clean_url( self ):
        url = self.cleaned_data.get( 'url' )
        if not url: 
            return ''

        filename, headers = urllib.urlretrieve( url )
        type = headers.get( 'Content-Type' )
        if not type or not mimetypes.guess_all_extensions( type ):
            raise forms.ValidationError( _( 'The file type is invalid: %s' % type ) )

        return SimpleUploadedFile( filename, open( filename ).read(), content_type = headers.get( 'Content-Type' ) )

    def clean( self ):
        image = self.cleaned_data.get( 'image' ) or self.cleaned_data.get( 'url' )
        if not image:
            raise forms.ValidationError( _( 'You must enter one of the options' ) )
        
        self.cleaned_data['image'] = image

        min_w, min_h = THUMBNAIL_DIMENSION

        dimension = get_image_dimensions( image )
        if dimension is None: w, h = 0, 0
        else: 
            w, h = dimension

        if w < min_w or h < min_h:
            raise forms.ValidationError(
                _( "You must select a image with a minimum of %(width)dx%(height)d pixels." % { 'width': min_w, 'height': min_h } )
            )

        return self.cleaned_data

film20/upload/views.py
import json, time

from django.core.cache import cache
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required

from .forms import UserUploadImageForm

@login_required
def upload_picture( request, template="upload/upload-image.html" ):
    return render( request, template )

@login_required
def upload_image( request ):

    data = {
        'success': False,
        'errors' : {
            '__all__': '#System error'
        },
    }

    if request.method == 'POST':
        form = UserUploadImageForm( request.POST, request.FILES )

        if form.is_valid():
            uploaded_image = form.save( commit=False )
            uploaded_image.uploaded_by = request.user

            uploaded_image.save()
            
            data['success'] = True
            data['image_id'] = uploaded_image.id
            data['image'] = uploaded_image.image.url

        else:
            data['errors'] = dict([(k, [unicode(e) for e in v]) for k,v in form.errors.items()])
    
    return HttpResponse( '<div id="response">%s</div>' % json.dumps( data ) )

film20/upload/templates/upload/upload-image-form.html
{% load i18n %}
<form id="{{ id }}" class="upload-image-form" action="{% url upload-image %}" method="post" enctype="multipart/form-data" accept-charset="utf-8">
    {% csrf_token %}
    <p>
        <label for="id_url">{% trans "Provide image URL" %}:</label>
        <input id="id_url" type="text" name="url">
        <input id="get_from_url" type="button" value="{% trans "Upload" %}"/>
    </p>
    <p>
        <label for="id_image">{% trans "or upload from your hard drive" %}:</label>
        <input id="id_image" type="file" name="image">
    </p>
    <p>
        <label>{% trans "Preview" %}</label>
        <div id="image-preview"></div>
    </p>
</form>

<script type="text/javascript" charset="utf-8">
    (function($) {
        $.fn.uploadImage = function( options ) {
            options = $.extend({
                error  : function() {},
                success: function() {}
            }, options );

            return this.each( function(){
                var $this = $( this ),
                    $preview = $( '#image-preview', this ),
                    $image_field = $( "#id_image", this ),
                    $url_field = $( "#id_url", this ),
                    $url_fetch = $( "#get_from_url", this ),
                    $master_form = $( "#form__" + $this.attr( 'id' ) ),
                    callback = $this.attr( 'id' ) + '_callback';

                // iframe id
                var iframe_id = $this.attr( 'id' ) + "__iframe";

                // append iframe
                var $iframe = $( '<iframe></iframe>')
                    .attr({
                        'id'  : iframe_id,
                        'name': iframe_id,
                    })
                    .hide()
                    .appendTo( $this );

                // set form target to iframe
                $this.attr( 'target', iframe_id );

                // on submit action
                $this.bind( 'submit', function() {
                    $preview.html( '' );
                    $preview.addClass( 'loading' );

                    $iframe.load( function() {
                        // reset errors
                        $( '.upload-errors' ).remove();
                        
                        // read response
                        response = $iframe.contents().find( '#response' );
                        try {
                            var json = $.parseJSON( response.html() );
                            
                            if ( json.success ) {
                                var $img = $( '<img/>' )
                                    .attr({
                                        'src': json.image
                                    })
                                    .hide()
                                    .appendTo( $preview );

                                // show image after load
                                $img.load( function() {
                                    $preview.removeClass( 'loading' );
                                    $img.fadeIn();
                                    
                                    // set values
                                    $( "#id_uploaded_image", $master_form ).val( json['image_id'] );
                                    $( "#url_uploaded_image", $master_form ).val( json['image'] );
                                    
                                    // and fire callback ..
                                    if( window[ callback ] ) {
                                        window[ callback ] ( json );
                                    }
                                });

                            } else {
                                $preview.removeClass( 'loading' );
                                
                                $( "#id_uploaded_image", $master_form ).val( '' )
                                $( "#url_uploaded_image", $master_form ).val( '' )

                                for ( var key in json.errors ) {
                                    var $errorlist = $( '<ul class="upload-errors errorlist"><ul>' )
                                    for ( var i = 0; i < json.errors[key].length; i++ ) {
                                        $errorlist.append( '<li>' + json.errors[key][i] + '</li>' )
                                    }

                                    if ( key == '__all__' ) {
                                        $errorlist.prependTo( $this )
                                    } else {
                                        $errorlist.prependTo( '#id_' + key )
                                    }
                                }
                            }
                        } catch ( err ) {
                            $preview.removeClass( 'loading' );
                                
                            $( "#id_uploaded_image", $master_form ).val( '' );
                            $( "#url_uploaded_image", $master_form ).val( '' );
                            var $errorlist = $( '<ul class="upload-errors errorlist"><ul>' );
                            $errorlist.append( gettext('<li>Server error, please try again</li>') );
                            $errorlist.prependTo( $this );
                        }
                        $iframe.unbind( 'load' );
                    });

                });
                
                // bind events
                $image_field.change( function() {
                    $url_field.val( '' )
                    $this.submit();
                });

                $url_fetch.click( function() {
                    $image_field.val( '' )
                    $this.submit();
                });

            });
        };
    })( jQuery );

    $( function() {
        $( '#{{ id }}' ).uploadImage();
    });
</script>

film20/upload/templates/upload/upload-image.html
{% load upload_tags %}

<div id="main" class="upload-photo">

{% upload_image_form 'upload_photo' %}

<form id="form__upload_photo" action="{{ url }}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" id="id_uploaded_image" />
    <input type="hidden" id="url_uploaded_image" />
</form>
</div>